"""changed group_id to nullable and removed date column in expense

Revision ID: 2d09114d8a3f
Revises: 23289cbbf519
Create Date: 2025-03-11 11:54:08.548788

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d09114d8a3f"
down_revision: Union[str, None] = "23289cbbf519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("expenses", "group_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("expenses", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses",
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.alter_column("expenses", "group_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
