"""Add updated_at column to expenses and expense_splits

Revision ID: af9cb3da7000
Revises: 2d09114d8a3f
Create Date: 2025-03-27 12:59:54.498444

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af9cb3da7000"
down_revision: Union[str, None] = "2d09114d8a3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expense_splits", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column("expenses", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "updated_at")
    op.drop_column("expense_splits", "updated_at")
    # ### end Alembic commands ###
