"""Fixed UTC handling in datetime fields

Revision ID: ad6d8ca5d9fe
Revises: 2d09114d8a3f
Create Date: 2025-03-17 12:41:20.086341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad6d8ca5d9fe"
down_revision: Union[str, None] = "2d09114d8a3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("joined_at", sa.DateTime(), nullable=True))
    op.drop_column("groups", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("groups", "joined_at")
    # ### end Alembic commands ###
